## About Dataset
Context

This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

Content
5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.


Columns

- asin - ID of the product, like B000FA64PK
- helpful - helpfulness rating of the review - example: 2/3.
- overall - rating of the product.
- reviewText - text of the review (heading).
- reviewTime - time of the review (raw).
- reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
- reviewerName - name of the reviewer.
- summary - summary of the review (description).
- unixReviewTime - unix timestamp.

Acknowledgements


This dataset is taken from Amazon product data, Julian McAuley, UCSD website. http://jmcauley.ucsd.edu/data/amazon/

License to the data files belong to them.

Inspiration
- Sentiment analysis on reviews.
- Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
- Fake reviews/ outliers.
- Best rated product IDs, or similarity between products based on reviews alone.

## Best Practises
1. Preprocessing And Cleaning
2. Data Exploration 
3. Train Test split
4. BOW, TFIDF, Word2vec
5. Train ML algorithms

In [ ]:
# Load the dataset
import pandas as pd
data = pd.read_csv("all_kindle_review.csv")

In [ ]:
# display imported data
data

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000
...,...,...,...,...,...,...,...,...,...,...,...
11995,11995,2183,B001DUGORO,"[0, 0]",4,Valentine cupid is a vampire- Jena and Ian ano...,"02 28, 2014",A1OKS5Q1HD8WQC,lisa jon jung,jena,1393545600
11996,11996,6272,B002JCSFSQ,"[2, 2]",5,I have read all seven books in this series. Ap...,"05 16, 2011",AQRSPXLNEQAMA,TerryLP,Peacekeepers Series,1305504000
11997,11997,12483,B0035N1V7K,"[0, 1]",3,This book really just wasn't my cuppa. The si...,"07 26, 2013",A2T5QLT5VXOJAK,hwilson,a little creepy,1374796800
11998,11998,3640,B001W1XT40,"[1, 2]",1,"tried to use it to charge my kindle, it didn't...","09 17, 2013",A28MHD2DDY6DXB,"Allison A. Slater ""Gryphon50""",didn't work,1379376000
11999,11999,11398,B003370JUS,"[5, 6]",3,Taking Instruction is a look into the often hi...,"07 5, 2012",A3JUXLB4K9ZXCC,Dafna Yee,"If you like BDSM with a touch of romance, this...",1341446400

In [ ]:
# Data information or description
data.describe()

       Unnamed: 0.1    Unnamed: 0        rating  unixReviewTime
count   12000.00000  12000.000000  12000.000000    1.200000e+04
mean     5999.50000  10024.275667      3.250000    1.344537e+09
std      3464.24595  10502.233123      1.421619    4.369374e+07
min         0.00000      0.000000      1.000000    9.602496e+08
25%      2999.75000   2999.750000      2.000000    1.316218e+09
50%      5999.50000   5999.500000      3.500000    1.356826e+09
75%      8999.25000  12475.750000      4.250000    1.376870e+09
max     11999.00000  47770.000000      5.000000    1.405814e+09

In [ ]:
# To check the context of the the review ratings
df = data[["reviewText", "rating"]]
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [ ]:
# Size of the data
df.shape

(12000, 2)

In [8]:
df

                                              reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       3
1      Great short read.  I didn't want to put it dow...       5
2      I'll start by saying this is the first of four...       3
3      Aggie is Angela Lansbury who carries pocketboo...       3
4      I did not expect this type of book to be in li...       4
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       4
11996  I have read all seven books in this series. Ap...       5
11997  This book really just wasn't my cuppa.  The si...       3
11998  tried to use it to charge my kindle, it didn't...       1
11999  Taking Instruction is a look into the often hi...       3

[12000 rows x 2 columns]

In [ ]:
# To check Missing Values
data.isnull().sum()

Unnamed: 0.1       0
Unnamed: 0         0
asin               0
helpful            0
rating             0
reviewText         0
reviewTime         0
reviewerID         0
reviewerName      38
summary            2
unixReviewTime     0
dtype: int64

In [ ]:
# Handle missing values
df['reviewText'] = df['reviewText'].fillna('').astype(str)

C:\Users\Oso Mueez\AppData\Local\Temp\ipykernel_3628\3978867559.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].fillna('').astype(str)

In [ ]:
# 5 unique values in the rating columns
data["rating"].unique()

array([3, 5, 4, 2, 1])

In [ ]:
# Counts for each values
data["rating"].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [12]:
# Percentage of reviews with rating >= 3
percentage = (data["rating"] >= 3).mean() * 100
print(f"{percentage:.2f}%")

66.67%

## Preprocessing and Cleaning

In [ ]:
# Normalization
# Positive review is 1 and negative review is 0 ( 3 above, positive. Below 3, Negative)
df["rating"] = data["rating"].apply(lambda x: 0 if x < 3 else 1)

C:\Users\Oso Mueez\AppData\Local\Temp\ipykernel_3628\3626127343.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["rating"] = data["rating"].apply(lambda x:0 if x<3 else 1)

In [16]:
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [ ]:
# The proportion of the Normalized data
df["rating"].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [ ]:
# Convert all review text to lowercase for consistent text processing
df["reviewText"].str.lower()

0        jace rankin may be short, but he's nothing to ...
1        great short read.  i didn't want to put it dow...
2        i'll start by saying this is the first of four...
3        aggie is angela lansbury who carries pocketboo...
4        i did not expect this type of book to be in li...
                               ...
11995    valentine cupid is a vampire- jena and ian ano...
11996    i have read all seven books in this series. ap...
11997    this book really just wasn't my cuppa.  the si...
11998    tried to use it to charge my kindle, it didn't...
11999    taking instruction is a look into the often hi...
Name: reviewText, Length: 12000, dtype: object

In [ ]:
# 1. Lower All the cases
df["reviewText"] = df["reviewText"].str.lower()

C:\Users\Oso Mueez\AppData\Local\Temp\ipykernel_3628\2256800522.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviewText"]=df["reviewText"].str.lower()

In [20]:
df.head()

                                          reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [ ]:
# # Import the 're' module for working with regular expressions
# Import the Natural Language Toolkit (NLTK) library for processing and analysing human language
# Import the stopwords corpus from NLTK to remove the common words during text processing
# Download the stopwords datasets required by nltk

import re
import nltk
from nltk.corpus import stopwords
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to C:\Users\Oso
[nltk_data]     Mueez\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [23]:

# Import BeautifulSoup from the bs4 library.
# to parse HTML or XML documents and extract data.
from bs4 import BeautifulSoup

In [ ]:
# Make a copy to avoid SettingWithCopyWarning
df = df.copy()

# Load stopwords once (faster)
stop_words = set(stopwords.words('english'))

# Handle missing values
df['reviewText'] = df['reviewText'].fillna('').astype(str)

# 1. Remove URLs
df['reviewText'] = df['reviewText'].apply(
    lambda x: re.sub(r'https?://\S+|www\.\S+', '', x))

# 2. Remove HTML tags
df['reviewText'] = df['reviewText'].apply(
    lambda x: BeautifulSoup(x, 'lxml').get_text())

# 3. Remove special characters
df['reviewText'] = df['reviewText'].apply(
    lambda x: re.sub(r'[^a-zA-Z0-9\s-]', '', x))

# 4. Convert to lowercase
df['reviewText'] = df['reviewText'].apply(lambda x: x.lower())

# 5. Remove stopwords
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join(
    word for word in x.split()if word not in stop_words))

# 6. Remove extra spaces
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join(x.split()))

In [ ]:
# Display cleaned Text
df.head()

                                          reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [ ]:
# Lemmatizer

# Import WordNetLemmatizer from NLTK.
from nltk.stem import WordNetLemmatizer

In [ ]:
# Create an instance of the lemmatizer.
lemmatizer = WordNetLemmatizer()

In [30]:
def lemmatize_words(text):
    # Split the input text into individual words.
    # Apply lemmatization to each word using the lemmatizer.
    # Join the lemmatized words back into a single string with spaces.
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [ ]:

# Apply the lemmatize_words() function to each review
# in the 'reviewText' column using the apply() method.
# The lambda function passes each review (x) to the
# lemmatize_words() function.
# Store the lemmatized reviews back in the same column.
df['reviewText'] = df['reviewText'].apply(
    lambda x: lemmatize_words(x)
)

In [32]:
df.head()

                                          reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [ ]:
# import the train_test_split function from the sklearn.model_selection module.
# split the dataset into training and testing sets using the train_test_split() function.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['reviewText'], df['rating'],
                                                    test_size=0.20, random_state=42, stratify=df['rating'])

In [ ]:

# Import CountVectorizer to convert text into numerical features
# using the Bag of Words (BoW) technique.
from sklearn.feature_extraction.text import CountVectorizer

# Create a Bag of Words vectorizer.
# To Remove common English stop words and keep at most 10,000 features.
bow = CountVectorizer(
    stop_words="english",
    max_features=10000
)

# Learn the vocabulary from the training reviews and convert
# them into a numerical document-term matrix.
X_train_bow = bow.fit_transform(X_train).toarray()

# Convert the test reviews using the same vocabulary learned
# from the training data, without learning new vocabulary.
X_test_bow = bow.transform(X_test).toarray()

In [35]:
# Import TfidfVectorizer to convert text into numerical features
# based on the importance of words in each document.
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the TF-IDF vectorizer.
# Remove common English stop words and limit the vocabulary
# to a maximum of 10,000 features.
tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=10000
)

# Learn the vocabulary and calculate TF-IDF features
# from the training reviews.
X_train_tfidf = tfidf.fit_transform(X_train).toarray()

# Transform the test reviews using the vocabulary and
# IDF values learned from the training data.
X_test_tfidf = tfidf.transform(X_test).toarray()

In [36]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(9600, 10000))

In [37]:
X_train_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(9600, 10000))

In [ ]:
# Import the machine learning models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

# Evaluation Metrics
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
models = {
    "Naive Bayes": MultinomialNB(),
    "Logistic Regression": LogisticRegression(max_iter=1000, class_weight="balanced"),
    "Linear SVM": LinearSVC(),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),

}

In [ ]:
def train_models(models, X_train, X_test, y_train, y_test):

    # store the accuracy result for each model
    results = {}

    # train and evaluate each models in a dictionary format
    for name, model in models.items():

        print("\n")
        print("==============================")
        print(name)
        print("==============================")

        # model training
        model.fit(X_train, y_train)

        # Make predictions
        y_pred = model.predict(X_test)

        # accuracy score
        accuracy = accuracy_score(y_test, y_pred)

        results[name] = accuracy
        print("Accuracy:", accuracy)

        # Detailed performance report using the classification report output
        print("\nClassification Report:")
        print(classification_report(y_test, y_pred)
              )

        # Confusion matrix
        print("\nConfusion Matrix:")
        print(confusion_matrix(y_test, y_pred)
              )

    # Return all model evaluation results
    return results

In [ ]:
# Train and evaluate the machine learning models
# using Bag of Words (BoW) features.
bow_results = train_models(
    models,
    X_train_bow,
    X_test_bow,
    y_train,
    y_test
)

==============================
Naive Bayes
==============================
Accuracy: 0.8345833333333333

Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.80      0.76       800
           1       0.90      0.85      0.87      1600

    accuracy                           0.83      2400
   macro avg       0.81      0.83      0.82      2400
weighted avg       0.84      0.83      0.84      2400


Confusion Matrix:
[[ 643  157]
 [ 240 1360]]


==============================
Logistic Regression
==============================
Accuracy: 0.8295833333333333

Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.78      0.75       800
           1       0.88      0.86      0.87      1600

    accuracy                           0.83      2400
   macro avg       0.81      0.82      0.81      2400
weighted avg       0.83      0.83      0.83      2400


Confusion Matrix:
[[ 621  179]
 [ 230 1370]]


==============================
Linear SVM
==============================
Accuracy: 0.7958333333333333

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.68      0.69       800
           1       0.84      0.85      0.85      1600

    accuracy                           0.80      2400
   macro avg       0.77      0.77      0.77      2400
weighted avg       0.79      0.80      0.80      2400


Confusion Matrix:
[[ 547  253]
 [ 237 1363]]


==============================
Random Forest
==============================
Accuracy: 0.8104166666666667

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.53      0.65       800
           1       0.80      0.95      0.87      1600

    accuracy                           0.81      2400
   macro avg       0.82      0.74      0.76      2400
weighted avg       0.82      0.81      0.80      2400


Confusion Matrix:
[[ 420  380]
 [  75 1525]]


==============================
Decision Tree
==============================
Accuracy: 0.7075

Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.56      0.56       800
           1       0.78      0.78      0.78      1600

    accuracy                           0.71      2400
   macro avg       0.67      0.67      0.67      2400
weighted avg       0.71      0.71      0.71      2400


Confusion Matrix:
[[ 445  355]
 [ 347 1253]]

 Class 0: Precision is 73%, meaning that 73% of reviews predicted as class 0 were actually class 0. Recall is 80%, the model correctly identified 80% of all actual class 0 reviews.
 Class 1: Precision is 90%, and recall is 85%. The model performs better at identifying class 1 than class 0 overall.
 The model is better at predicting class 1, based on its higher precision and F1-score.



 So, based on this confusion matrix, Logistic Regression has 70.75% accuracy, which is lower than Naive Bayes at 83.46%.

 Naive Bayes performs better than Logistic Regression on the supplied test data. 
 It makes 305 more correct predictions and has about 12.71 percentage points higher accuracy.

In [42]:

# Train and evaluate the machine learning models
# using TF-IDF numerical features.
tfidf_results = train_models(
    models,
    X_train_tfidf,
    X_test_tfidf,
    y_train,
    y_test
)

==============================
Naive Bayes
==============================
Accuracy: 0.7908333333333334

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.41      0.57       800
           1       0.77      0.98      0.86      1600

    accuracy                           0.79      2400
   macro avg       0.84      0.70      0.71      2400
weighted avg       0.82      0.79      0.76      2400


Confusion Matrix:
[[ 327  473]
 [  29 1571]]


==============================
Logistic Regression
==============================
Accuracy: 0.845

Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.81      0.78       800
           1       0.90      0.86      0.88      1600

    accuracy                           0.84      2400
   macro avg       0.82      0.84      0.83      2400
weighted avg       0.85      0.84      0.85      2400


Confusion Matrix:
[[ 652  148]
 [ 224 1376]]


==============================
Linear SVM
==============================
Accuracy: 0.8333333333333334

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.70      0.74       800
           1       0.86      0.90      0.88      1600

    accuracy                           0.83      2400
   macro avg       0.82      0.80      0.81      2400
weighted avg       0.83      0.83      0.83      2400


Confusion Matrix:
[[ 562  238]
 [ 162 1438]]


==============================
Random Forest
==============================
Accuracy: 0.7983333333333333

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.49      0.62       800
           1       0.79      0.95      0.86      1600

    accuracy                           0.80      2400
   macro avg       0.81      0.72      0.74      2400
weighted avg       0.81      0.80      0.78      2400


Confusion Matrix:
[[ 389  411]
 [  73 1527]]


==============================
Decision Tree
==============================
Accuracy: 0.7058333333333333

Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.57      0.56       800
           1       0.78      0.77      0.78      1600

    accuracy                           0.71      2400
   macro avg       0.67      0.67      0.67      2400
weighted avg       0.71      0.71      0.71      2400


Confusion Matrix:
[[ 456  344]
 [ 362 1238]]

In [43]:
import pandas as pd
import matplotlib.pyplot as plt


# results
bow_results = {
    'Naive Bayes': 0.8266666666666667,
    'Logistic Regression': 0.83125,
    'Linear SVM': 0.7991666666666667,
    'Random Forest': 0.80125,
    'Decision Tree': 0.7108333333333333
}

tfidf_results = {
    'Naive Bayes': 0.79625,
    'Logistic Regression': 0.8308333333333333,
    'Linear SVM': 0.83125,
    'Random Forest': 0.7970833333333334,
    'Decision Tree': 0.68875
}

# Combining results into a DataFrame
comparison_df = pd.DataFrame({
    "Model": list(bow_results.keys()),
    "Bag of Words": list(bow_results.values()),
    "TF-IDF": list(tfidf_results.values())
})


print(comparison_df)

                 Model  Bag of Words    TF-IDF
0          Naive Bayes      0.826667  0.796250
1  Logistic Regression      0.831250  0.830833
2           Linear SVM      0.799167  0.831250
3        Random Forest      0.801250  0.797083
4        Decision Tree      0.710833  0.688750

In [47]:
# Install the Gensim library for natural language processing
# and word embedding techniques.
!pip install gensim

Requirement already satisfied: gensim in C:\Users\Oso Mueez\anaconda3\Lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in C:\Users\Oso Mueez\AppData\Roaming\Python\Python313\site-packages (from gensim) (2.4.0)
Requirement already satisfied: scipy>=1.7.0 in C:\Users\Oso Mueez\AppData\Roaming\Python\Python313\site-packages (from gensim) (1.17.0)
Requirement already satisfied: smart_open>=1.8.1 in C:\Users\Oso Mueez\anaconda3\Lib\site-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in C:\Users\Oso Mueez\AppData\Roaming\Python\Python313\site-packages (from smart_open>=1.8.1->gensim) (1.17.3)

[notice] A new release of pip is available: 26.1.2 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [45]:
from gensim.models import Word2Vec

In [48]:
X_train

1147     although holly starting get nerve want fling t...
10480    find hard believe four five star rating book e...
7898     read sylvia day book really enjoyed loved bare...
1230     boring boring boring didnt even bother finish ...
9029     going read jeri smith ready crow trilogy found...
                               ...
10349    great read knowledgeable tribe michigan would ...
11572    oh gosh wasnt one boring there premise endeavo...
7168     liked h stuck gun serious getting back wife worth
4923     ok really interesting ok read aa done done don...
9154     people read fantasy want believe magic somethi...
Name: reviewText, Length: 9600, dtype: object

In [ ]:
# training the model using word2vec

In [ ]:
# X_train_tokens

In [ ]:
# Tokenize the X_trains
X_train_tokens = [review.split() for review in X_train]
X_test_tokens = [review.split() for review in X_test]

In [ ]:
# Generate the word2vec model and implement it on the data
from gensim.models import Word2Vec

word2vec_model = Word2Vec(
    sentences=X_train_tokens,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    epochs=20
)

In [ ]:
# Transform text reviews into numerical features using Word2Vec embeddings.

In [ ]:
import numpy as np
"""
    Convert a single review (list of words) into one Word2Vec vector
    
"""

# Get the Word2Vec embedding for each word that exists in the trained vocabulary


def review_vector(review):
    vectors = [
        word2vec_model.wv[word]
        for word in review
        if word in word2vec_model.wv
    ]

    # return a vector of zeros (100 dimensions)
    # If no words from the review are found in the Word2Vec vocabulary
    if len(vectors) == 0:
        return np.zeros(100)

    return np.mean(vectors, axis=0)


X_train_word2vec = np.array([review_vector(r) for r in X_train_tokens])
X_test_word2vec = np.array([review_vector(r) for r in X_test_tokens])

In [55]:
vector = word2vec_model.wv["movie"]

print(vector.shape)

(100,)

In [ ]:
# To find the top 10 words similar to good
word2vec_model.wv.most_similar("good", topn=10)

[('decent', 0.6732579469680786),
 ('great', 0.6307032108306885),
 ('fantastic', 0.5133547782897949),
 ('awesome', 0.49238985776901245),
 ('nice', 0.46951693296432495),
 ('amazing', 0.4667775332927704),
 ('excellent', 0.45729926228523254),
 ('exciting', 0.4565315842628479),
 ('better', 0.4541319012641907),
 ('interesting', 0.45376279950141907)]

In [ ]:
# word2vec_model.wv['book']

In [ ]:
# To find the words similar to books
word2vec_model.wv.similar_by_word('book')

[('booki', 0.592400312423706),
 ('story', 0.5717602968215942),
 ('novel', 0.5652016997337341),
 ('disappointed', 0.5406913757324219),
 ('read', 0.5382235050201416),
 ('preview', 0.5232470035552979),
 ('disappointing', 0.5213388800621033),
 ('probably', 0.5089148879051208),
 ('bookit', 0.5044653415679932),
 ('bookread', 0.49670687317848206)]

In [61]:
X_train_word2vec.shape

(9600, 100)

**Standardization**

In [ ]:
# To examines the training data and calculates:

# Mean of each feature
# Standard deviation of each feature

In [63]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_word2vec_scaled = scaler.fit_transform(
    X_train_word2vec
)

X_test_word2vec_scaled = scaler.transform(
    X_test_word2vec
)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

# Machine learning Models
word2vec_models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, class_weight="balanced"),
    "Random Forest": RandomForestClassifier(random_state=42),
    "SVM": SVC(class_weight="balanced"),
    "Gaussian NB": GaussianNB()
}

In [ ]:
# Train and evaluate multiple machine learning models using the scaled Word2Vec features
word2vec_results = train_models(
    word2vec_models,
    X_train_word2vec_scaled,
    X_test_word2vec_scaled,
    y_train,
    y_test
)

==============================
Logistic Regression
==============================
Accuracy: 0.82375

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.83      0.76       800
           1       0.91      0.82      0.86      1600

    accuracy                           0.82      2400
   macro avg       0.80      0.82      0.81      2400
weighted avg       0.84      0.82      0.83      2400


Confusion Matrix:
[[ 663  137]
 [ 286 1314]]


==============================
Random Forest
==============================
Accuracy: 0.8045833333333333

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.59      0.67       800
           1       0.82      0.91      0.86      1600

    accuracy                           0.80      2400
   macro avg       0.79      0.75      0.76      2400
weighted avg       0.80      0.80      0.80      2400


Confusion Matrix:
[[ 473  327]
 [ 142 1458]]


==============================
SVM
==============================
Accuracy: 0.83

Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.81      0.76       800
           1       0.90      0.84      0.87      1600

    accuracy                           0.83      2400
   macro avg       0.81      0.83      0.81      2400
weighted avg       0.84      0.83      0.83      2400


Confusion Matrix:
[[ 651  149]
 [ 259 1341]]


==============================
Gaussian NB
==============================
Accuracy: 0.7608333333333334

Classification Report:
              precision    recall  f1-score   support

           0       0.61      0.78      0.68       800
           1       0.87      0.75      0.81      1600

    accuracy                           0.76      2400
   macro avg       0.74      0.76      0.75      2400
weighted avg       0.78      0.76      0.77      2400


Confusion Matrix:
[[ 621  179]
 [ 395 1205]]

| Model               |   Accuracy | Negative Recall | Positive Recall | Weighted F1 |
| ------------------- | ---------: | --------------: | --------------: | ----------: |
| **SVM**             | **83.71%** |         **83%** |         **84%** |    **0.84** |
| Logistic Regression |     81.83% |             82% |             82% |        0.82 |
| Random Forest       |     80.83% |             61% |             91% |        0.80 |
| Gaussian NB         |     76.33% |             78% |             75% |        0.77 |

SVM is the best-performing model in this comparison. It has the highest accuracy and weighted F1-score, alongside balanced recall for negative and positive reviews. Logistic Regression is a close second and also provides balanced classification performance.

Random Forest is particularly effective at identifying positive reviews, but its lower negative recall may make it less suitable if detecting negative customer feedback is a priority.

One important qualification: these conclusions assume that all four models were evaluated on the same test set using the same class definitions. Also, because precision is not included in your table, the results do not show how reliable each model's positive and negative predictions are.